version: "3"
services:
# Run the postgres database
  db:
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=repa_api_dev
      - PGDATA=/pgdata

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - "8080"
      - "8081"
    env_file:
      - .env
    depends_on:
      - db
    links:
      - "db:database"
